# Generated by Django 3.0.7 on 2020-06-30 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instaHandle', models.URLField(blank=True, null=True)),
                ('home', models.CharField(blank=True, max_length=255, null=True)),
                ('instituition', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('member', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default=' ')),
                ('verified', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
                ('place', models.CharField(blank=True, default=' ', max_length=100)),
                ('tag', models.TextField(blank=True, default=' ', max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_store.photographer')),
            ],
        ),
    ]
