# Generated by Django 3.0.7 on 2020-06-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_store', '0002_images_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='gender',
        ),
        migrations.AddField(
            model_name='photographer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Say')], default='Male', max_length=10),
        ),
    ]
