# Generated by Django 3.0.7 on 2020-06-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_store', '0003_auto_20200630_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
