# Generated by Django 3.1 on 2020-08-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_store', '0007_auto_20200817_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='instaHandle',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
