# Generated by Django 3.1 on 2020-08-17 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_store', '0008_auto_20200817_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_model', to='image_store.images')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
