# Generated by Django 3.1.4 on 2020-12-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_store', '0009_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
